# Reinforcement Learning Group Assignment 1 (a&b)
## Enzo Keuning (12878502), Hsi Yun Chien (12534919), Younjoo Mo (12475440)


In [1]:
import numpy as np


### Question (a):

In [2]:
#0: rent out; 1: maintanence
action = range(2)
states = (1, 2, 3, 4) 
num_of_states = len(states)
negative_infinity = float('-inf')
rewards = np.array([[60, negative_infinity], [60, -40], [60, -40], [negative_infinity, -100]])


#define state transition probability
p = np.array([[[0.8, 0.1, 0.1, 0], [0, 0, 0, 0]], 
              [[0, 0.6, 0.3, 0.1], [1, 0, 0, 0]],
              [[0, 0, 0.5, 0.5], [1, 0, 0, 0]], 
              [[0, 0, 0, 0],[1, 0, 0, 0]]])


v       = [0, 0, 0, -100]



pi      = np.zeros(num_of_states, dtype=int)



In [3]:
r = []
for i in range(8):
#iterate 8 times
    k = []
    for s in range(0,4):
        if i == 0:
            vold = v[s]
        else:
            vold = r[i-1][s]
        vmax = np.zeros(4)
        if i == 0:
            q = rewards[s] + np.dot(p[s],v)
        else:
            q = rewards[s] + np.dot(p[s],r[i-1])
        k.append(max(q))  
        vmax[s]  = max(vmax[s], abs(vold-k[s]))
        pi[s] = np.argmax(q)
    r.append(k)
    r[i] = np.round(r[i],1)
    print(f"{r[i]}     Optimal policy for day {8-i}: {pi}")

[  60.   50.   10. -100.]     Optimal policy for day 8: [0 0 0 1]
[114.  83.  20. -40.]     Optimal policy for day 7: [0 0 1 1]
[161.5 111.8  74.   14. ]     Optimal policy for day 6: [0 0 1 1]
[207.8 150.7 121.5  61.5]     Optimal policy for day 5: [0 0 1 1]
[253.5 193.  167.8 107.8]     Optimal policy for day 4: [0 0 1 1]
[298.9 236.9 213.5 153.5]     Optimal policy for day 3: [0 0 1 1]
[344.2 281.5 258.9 198.9]     Optimal policy for day 2: [0 0 1 1]
[389.4 326.5 304.2 244.2]     Optimal policy for day 1: [0 0 1 1]


### Question (b):

In [4]:
p = np.array([[[0.8, 0.1, 0.1, 0], [0, 0, 0, 0]],
              [[0, 0.6, 0.3, 0.1], [1, 0, 0, 0]],
              [[0, 0, 0.5, 0.5], [1, 0, 0, 0]], 
              [[0, 0, 0, 0], [1, 0, 0, 0]]])
rewards_b = np.array([ [60, negative_infinity], [60, -40], [60, -40], [negative_infinity, -100]])

v_b       = np.zeros(4)
pi_b      = np.zeros(4, dtype=np.int)
states_b  = (1, 2, 3, 4)
actions = range(2)
gamma   = 0.9

for s in range(0,4):
    v_b[s]  = max(rewards_b[s,])
    pi_b[s] = np.argmax(rewards_b[s,])
    
vmax_b = 999
while vmax_b > 1.0e-5:
    vmax_b = 0
    for s in range(0,4):
        vold_b  = v_b[s]
        q_b     = rewards_b[s] + gamma*np.dot(p[s],v_b)
        v_b[s]  = max(q_b)
        vmax_b  = max(vmax_b, abs(vold_b-v_b[s]))
        pi_b[s] = np.argmax(q_b)        
        #print(v, pi)
    #print(vmax)

print("Optimal policy    : ", pi_b)
print("Estimated v-values: ", v_b)


Optimal policy    :  [0 0 1 1]
Estimated v-values:  [473.90182244 421.1830066  386.5116402  326.5116402 ]
